name: gitee

on: page_build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:linyuansup/synthesizer-v-r2-docs.git
          destination-repo: git@gitee.com:linyuansup/synthesizer-v-r2-docs.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: linyuansup
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: linyuansup/synthesizer-v-r2-docs
          branch: gh-pages
