name: markdown deploy

on: 
  push:
    branches: 
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run pdf

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: Synthesizer-V-R2-User-Manual.pdf
      env:
        GITHUB_TOKEN: ${{secrets.key}}
        
    - run: npm run docs:build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{secrets.key}}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: docs/.vuepress/dist
