name: release deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-deploy:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run pdf

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: Synthesizer-V-R2-User-Manual.pdf
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}